Update QuoteList.ts
nhcarrigan/inspiration-bot pull request #29
Opened 2022-03-02 04:24 UTC by fab33150

# Pull Request

## Description:
Adds a new inspirational quote

## Related Issue:

Closes #XXXXX

2022-03-02 14:58 UTC, gtchakama submitted a review, later dismissed

2022-03-02 16:27 UTC, nhcarrigan requested changes

2022-03-02 16:27 UTC, nhcarrigan commented on src/config/QuoteList.ts
> +  }
```suggestion
  },
```
Needs a trailing comma. 😁

2022-03-03 02:21 UTC, fab33150 reviewed
added trailing comma

2022-03-03 14:52 UTC, nhcarrigan approved these changes
Looks good to me!

2022-03-03 14:53 UTC, merged

2022-03-03 14:53 UTC, nhcarrigan commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.