NewQuote
nhcarrigan/inspiration-bot pull request #38
Opened 2022-03-04 02:36 UTC by CQW-Code

Signed-off-by: Christopher Watkin <chriswatkin@gmail.com>

# Pull Request

## Description:
Added two new quotes

Added two new quotes

## Related Issue:
  No issues and no issue # 

Closes #XXXXX

2022-03-04 05:00 UTC, nhcarrigan requested changes
Some linter fixes 🙂

2022-03-04 05:00 UTC, nhcarrigan commented on src/config/QuoteList.ts
> +  },
```suggestion
    author: "David Rossi- Criminal Minds",
  },
```

2022-03-04 05:00 UTC, nhcarrigan commented on src/config/QuoteList.ts
> +    author:  "A fortune cookie quote",
```suggestion
    author: "A fortune cookie quote",
```

2022-03-04 05:00 UTC, nhcarrigan commented on src/config/QuoteList.ts
> +  }
```suggestion
  },
```

2022-03-05 22:49 UTC, CQW-Code commented
Thank you- will fix those in the next day or so- it's been a while since I've used everything (only VBA at work...a little :) )

I

2022-03-06 19:51 UTC, CQW-Code commented
updated- I hope I did it right this time.   :)

2022-03-06 20:04 UTC, nhcarrigan approved these changes
Looks good to me!

2022-03-06 20:04 UTC, merged